### ISSUE TITLE
Write Permissions Service Responses

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss-labs/taco#188] opened 2018-02-06 22:48 UTC
- [ ] Hard coded initial permissions responses for create/update/get/etc

**Comment by jcoyne** [comment] 2018-02-22 17:57
@aaron-collier is this a duplicate of #186?

**Comment by aaron-collier** [comment] 2018-02-22 19:15
I don't think so, this is for the coding of what these responses should be while #186 is the swagger spec... Though, if this responses are coded into the swagger spec, then yes it is.

**Closed** 2018-02-27 16:15 UTC
Labels: in progress
