### ISSUE TITLE
Return DeleteResource back to codebase

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/taco#306] opened 2018-03-13 21:48 UTC
post #295

**Comment by jcoyne** [comment] 2018-03-14 01:13
This feels like a duplicate of #261. I'm not sure we need a new ticket.

**Comment by cmh2166** [comment] 2018-03-14 02:27
@aaron-collier cool? This is coming from a point in your PR being reviewed now

**Comment by aaron-collier** [comment] 2018-03-14 03:03
I'm OK with closing this as the point of "LATER:" was that there was an outstanding PR that shouldn't block my PR but will need to be rebased once #295 is merged, so I agree that we don't actually need this ticket.

**Closed by aaron-collier** 2018-03-14 03:03 UTC
Labels: next

**Comment by cmh2166** [comment] 2018-03-14 04:05
you didn't write "LATER" on that PR, so needed to confirm what work was where.
